# docker run --name postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 arm64v8/postgres
version: '3.7'
services:
  postgres:
    image: arm64v8/postgres
    container_name: postgres_test
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/create_tables.sql

