---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: offer-price-api
    version: v1
  name: offer-price-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: grpc
      port: 9010
      targetPort: 9010
  selector:
    app: offer-price-api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: offer-price-api
    version: v1
  name: offer-price-api-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer-price-api
      version: v1
  template:
    metadata:
      labels:
        app: offer-price-api
        version: v1
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OFR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: OFR_PASSWORD
                  name: offer-api-secret
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OFR_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: OFR_HOSTNAME
                  name: offer-api-config-map
            - name: OFR_PORT
              valueFrom:
                configMapKeyRef:
                  key: OFR_PORT
                  name: offer-api-config-map
            - name: OFR_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: OFR_USERNAME
                  name: offer-api-config-map
            - name: OFR_DBNAME
              valueFrom:
                configMapKeyRef:
                  key: OFR_DBNAME
                  name: offer-api-config-map
          image: docker.io/kmmraj/offer-price-api:1.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: offer-price-api
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9010
              name: grpc
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: offer-price-api
    version: v2
  name: offer-price-api-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: offer-price-api
      version: v2
  template:
    metadata:
      labels:
        app: offer-price-api
        version: v2
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OFR_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: OFR_PASSWORD
                  name: offer-api-secret
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OFR_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: OFR_HOSTNAME
                  name: offer-api-config-map
            - name: OFR_PORT
              valueFrom:
                configMapKeyRef:
                  key: OFR_PORT
                  name: offer-api-config-map
            - name: OFR_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: OFR_USERNAME
                  name: offer-api-config-map
            - name: OFR_DBNAME
              valueFrom:
                configMapKeyRef:
                  key: OFR_DBNAME
                  name: offer-api-config-map
          image: docker.io/kmmraj/offer-price-api:1.0.2-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: offer-price-api
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9010
              name: grpc
              protocol: TCP
